CREATE TABLE `wcf1_user_guestbook` (
  `id` INT(10) UNSIGNED NOT NULL auto_increment,
  `userID` INT(10) UNSIGNED NOT NULL,
  `fromUserID` INT(10) UNSIGNED NOT NULL,
  `fromUsername` VARCHAR(255) DEFAULT NULL,
  `text` MEDIUMTEXT DEFAULT NULL,
  `enableSmilies` TINYINT(1) NOT NULL,
  `enableHtml` TINYINT(1) NOT NULL,
  `enableBBCodes` TINYINT(1) NOT NULL,
  `entryTime` INT(10) UNSIGNED NOT NULL,
  `updateTime` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `updateUserID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `comment` VARCHAR(2000) DEFAULT NULL,
  `commentTime` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY  (`id`),
  INDEX `userID` (`userID`)
  ) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `wcf1_user_guestbook_header` (
  `userID` INT(10) UNSIGNED NOT NULL,
  `userLastVisit` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `userLastCommentTime` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `lastEntryUserID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `lastEntryUsername` VARCHAR(255) DEFAULT NULL,
  `lastEntry` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `entries` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `newEntries` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `views` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `visitorID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `visitorLastVisit` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `locked` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `lockTime` INT(10) UNSIGNED DEFAULT NULL,
  `lockUserID` INT(10) UNSIGNED DEFAULT NULL,
  PRIMARY KEY  (`userID`)
  ) ENGINE=MyISAM DEFAULT CHARSET=utf8;
